language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose -f docker-compose.dev.yml run backend sh -c "python manage.py test && flake8"