version: "3.7"

services:
  backend:
    container_name: web
    build:
      context: ./backend
      dockerfile: scripts/dev/Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=devpassword
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    command: /start_dev.sh
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=central
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpassword
    ports:
    - 5444:5432
