version: "3.7"

services:
  backend:
    container_name: web
    build:
      context: ./backend
      dockerfile: scripts/dev/Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=devpassword
    expose:
      - 8000
    volumes:
      - ./backend:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    command: /start_dev.sh
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=central
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpassword
    ports:
      - 5444:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build:
      context: ./nginx/dev
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - backend


volumes:
  postgres_data:
  static_volume:
  media_volume:
